### ISSUE TITLE
Can't prettify an expression that uses missing/valid?

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#37]
This snippet:

expected = '(endtime > "2016-12-04T23:45:21+00:00") or ((disposition != 1 and (missing(exit_status) or exit_status >= 1)) or (disposition == 0 and exit_status == 0) or (disposition == 0 and exit_status == 1) or (missing(gender)) or (missing(cassdma2012_full)) or (missing(presvote16x)) or (missing(child18)) or (missing(employ)) or (age < 16 and age > 99))'
ds.exclude(expected)
print(prettify(ds.resource.exclusion.body.expression, ds))

Generated this traceback:

Traceback (most recent call last):
  File "examples\refactored.py", line 144, in <module>
    print(prettify(forked_ds.resource.exclusion.body.expression, forked_ds))
  File "c:\users\ferna\src\scrunch\scrunch\expressions.py", line 675, in prettify
    return _process(_resolve_variables(expr))
  File "c:\users\ferna\src\scrunch\scrunch\expressions.py", line 662, in _process
    args = [_process(arg, _func) for arg in fragment['args']]
  File "c:\users\ferna\src\scrunch\scrunch\expressions.py", line 662, in <listcomp>
    args = [_process(arg, _func) for arg in fragment['args']]
  File "c:\users\ferna\src\scrunch\scrunch\expressions.py", line 662, in _process
    args = [_process(arg, _func) for arg in fragment['args']]
  File "c:\users\ferna\src\scrunch\scrunch\expressions.py", line 662, in <listcomp>
    args = [_process(arg, _func) for arg in fragment['args']]
  File "c:\users\ferna\src\scrunch\scrunch\expressions.py", line 662, in _process
    args = [_process(arg, _func) for arg in fragment['args']]
  File "c:\users\ferna\src\scrunch\scrunch\expressions.py", line 662, in <listcomp>
    args = [_process(arg, _func) for arg in fragment['args']]
  File "c:\users\ferna\src\scrunch\scrunch\expressions.py", line 662, in _process
    args = [_process(arg, _func) for arg in fragment['args']]
  File "c:\users\ferna\src\scrunch\scrunch\expressions.py", line 662, in <listcomp>
    args = [_process(arg, _func) for arg in fragment['args']]
  File "c:\users\ferna\src\scrunch\scrunch\expressions.py", line 673, in _process
    return _transform(_func, args, nest=nest)
  File "c:\users\ferna\src\scrunch\scrunch\expressions.py", line 631, in _transform
    raise Exception('Unknown function "%s"' % f)
Exception: Unknown function "is_missing"

**Comment by xbito** [comment]
Should be just a matter of bringing this commit to master: https://github.com/Crunch-io/scrunch/commit/96d68aae0e7e2d7cf30f1e275ccb983946d16300
